# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160918_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 22, 24, 44, 983184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 22, 24, 44, 983184, tzinfo=utc)),
        ),
    ]
