# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-23 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160918_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 23, 18, 45, 32, 382881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 23, 18, 45, 32, 383238, tzinfo=utc)),
        ),
    ]
